---
- name: Install zsh and autojump packages
  become: true  
  ansible.builtin.package:
    name:
      - git
      - wget
      - curl
      - zsh
      - autojump
    state: present
    
- name: Create .zshrc file
  ansible.builtin.command: touch ~/.zshrc

- name: Change default shell to zsh
  become: true
  ansible.builtin.shell: chsh -s $(which zsh) {{ ansible_env.USER }}

- name: Include tasks for Ruby installation
  ansible.builtin.include_tasks: ruby.yml

- name: Create .antigen directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.antigen"
    state: directory

- name: Download antigen.zsh
  ansible.builtin.get_url:
    url: https://git.io/antigen
    dest: "{{ ansible_env.HOME }}/.antigen/antigen.zsh"

- name: Copy .antigen configuration file
  ansible.builtin.template:
    src: templates/antigen.config.j2
    dest: "{{ ansible_env.HOME }}/.antigen/config"

- name: Enable antigen by sourcing it in ~/.zshrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    prepend_newline: true 
    marker: "# Antigen {mark} ---------------------------------"
    block: |
      # Load Antigen
      source ~/.antigen/antigen.zsh

      # Load Antigen configurations
      source ~/.antigen/config

- name: Copy p10k theme config
  ansible.builtin.copy:
    src: templates/p10k.zsh
    dest: "{{ ansible_env.HOME }}/.p10k.zsh"

- name: Modify .zshrc for p10k theme
  block: 
    - name: Add instant prompt block at the beginning of the file.
      ansible.builtin.blockinfile: 
        path: "{{ ansible_env.HOME }}/.zshrc"
        insertbefore: BOF
        append_newline: true 
        marker: "# Powerlevel10k instant prompt {mark} ---------------------------------"
        block: |
          # Should stay close to the top of ~/.zshrc.
          # Initialization code that may require console input (password prompts, [y/n]
          # confirmations, etc.) must go above this block; everything else may go below.
          if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
            source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
          fi

    - name: Add Powerlevel10k theme script block.
      ansible.builtin.blockinfile: 
        path: "{{ ansible_env.HOME }}/.zshrc"
        prepend_newline: true 
        marker: "# Powerlevel10k theme {mark} ---------------------------------"
        block: |
          # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
          [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
